version: '3.8'
services:
  db:
    image: "postgres:14.1-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: dwh_admin
      POSTGRES_USER: dwh_admin
      POSTGRES_PASSWORD: dwh_admin
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - dwh_collect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    depends_on:
      db:
        condition: service_healthy
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./dwh_collect/settings/.env
    networks:
      - dwh_collect

#volumes:
#   pgdata:
#      driver: local

networks:
  dwh_collect:
    driver: bridge